// Task seed for GDPRcompliant.eu — authored source of truth.
// `node scripts/tasks.mjs init` explodes this into tasks/<ID>.md, one file per task.
// The generator NEVER overwrites an existing task file: once generated, the .md is
// the source of truth and this file is history. Add new tasks here, re-run init.

export const streams = {
  X: 'Prototype — the non-functional UI, reviewed before anything is built behind it',
  F: 'Foundations — repo, schema, tenancy, queue, test harness',
  S: 'Scanner — the three-pass crawl and layer-one findings',
  R: 'Remedies — the catalogue, the invariant, the guides',
  C: 'Case — the object everything hangs on',
  U: 'Web — front door, case page, trust page, guides',
  D: 'Deep scan — public record and the contract chain',
  A: 'Agent — graph, rules, planner, workers, verifier',
  G: 'Generators — policy, DPA, register, evidence pack',
  P: 'People — roles, invitations, shared progress',
  L: 'Lanes — qualification, consultant view, referral',
  I: 'International — jurisdiction bindings and locales',
  O: 'Ops — security, retention, delivery',
  V: 'Advisor and reports — the status report, and the assistant that knows both the law and this case',
  T: 'Testing — the harness that stands in for a human tester',
};

export const phases = [
  { n: 0, name: 'Prototype', goal: 'Every screen, clickable, with nothing behind it. Frits signs it off before a line of engine code is written.' },
  { n: 1, name: 'Foundations', goal: 'A repo where a test can fail for the right reason.' },
  { n: 2, name: 'The wedge', goal: 'Public scanner live: three passes, 20 findings, every one with a fix.' },
  { n: 3, name: 'The case', goal: 'A numbered case that persists, shares and re-verifies.' },
  { n: 4, name: 'Depth', goal: 'Public record and contract chain. The part nobody else does.' },
  { n: 5, name: 'The system', goal: 'Graph, rules, planner, verifier. It stops being a scanner.' },
  { n: 6, name: 'Delivery', goal: 'Everything green, canary stable, handed over.' },
];

export const tasks = [
  // ---------------------------------------------------------------- PHASE 0
  // Non-functional throughout. No database, no queue, no model calls, no network.
  // Every screen reads from one shared mock dataset so the story stays consistent,
  // and that dataset becomes a real test fixture in phase 2. Components built here
  // are the components shipped later — this is a prototype, not a mockup to throw away.
  {
    id: 'X-01', stream: 'X', phase: 0, est: 'M', depends: [],
    title: 'Prototype scaffold and design system',
    goal: 'A Next.js app with the design tokens, type scale, both themes and the locale switch — deliberately minimal, no infrastructure.',
    acceptance: [
      'Runs with one command from a clean clone; no database, no services, no environment variables',
      'Deploys as a static build so Frits can click through it on a phone',
      'Tokens, type scale and severity colours defined once, matching the concept document',
      'Light and dark both designed, not inverted; severity readable in greyscale',
      'A visible PROTOTYPE marker on every screen so no screenshot is ever mistaken for a working product',
    ],
    verify: 'pnpm -F prototype build && pnpm -F prototype test:visual',
    notes: 'Keep it boring and small. F-01 later absorbs this app into the workspace without discarding a single component.',
  },
  {
    id: 'X-02', stream: 'X', phase: 0, est: 'S', depends: ['X-01'],
    title: 'The mock case dataset',
    goal: 'One fictional company, fully populated: 19 findings, evidence, timeline, vendors, supply chain, four colleagues, generated documents.',
    acceptance: [
      'A single typed dataset drives every screen — no screen invents its own numbers',
      'Findings span every severity and all five remedy kinds, including one no_solution',
      'Contains the awkward realities: an unresolved vendor, a not-determined clause, a regressed finding',
      'Shaped to the contracts in the concept document so phase 2 can adopt it as a test fixture unchanged',
    ],
    verify: 'pnpm -F prototype test:unit -- mock-dataset',
    notes: 'This is the highest-leverage half day in phase 0. Consistent fake data is what makes a prototype reviewable.',
  },
  {
    id: 'X-03', stream: 'X', phase: 0, est: 'M', depends: ['X-02'],
    title: 'Front door and scan progress',
    goal: 'One field, one button, and an honest-looking progress sequence through the three passes.',
    acceptance: [
      'Domain entry works by keyboard alone and is forgiving about format',
      'Progress shows the real stage names the engine will emit, timed to feel like the real thing',
      'A visible path for "this domain could not be reached"',
      'Mobile layout is designed, not merely tolerated',
    ],
    verify: 'pnpm -F prototype test:e2e -- front-door',
  },
  {
    id: 'X-04', stream: 'X', phase: 0, est: 'L', depends: ['X-02'],
    title: 'The case page',
    goal: 'The centrepiece: case number, progress track, timeline, findings list, fixes-ready count.',
    acceptance: [
      'No score in the header — fixes-ready and the track, per the concept document',
      'Timeline reads as a record of work done, and is legible printed',
      'Findings list is scannable at a glance: severity in form as well as colour',
      'Shows plainly, on the page, what is collected and who can see it',
      'Three states drawn: freshly opened, work in progress, and long-running under watch',
    ],
    verify: 'pnpm -F prototype test:e2e -- case-page',
  },
  {
    id: 'X-05', stream: 'X', phase: 0, est: 'M', depends: ['X-04'],
    title: 'Finding detail, evidence and the four remedies',
    goal: 'The screen that proves the product sells solutions rather than problems.',
    acceptance: [
      'Evidence drawer shows the raw request log, cookie table and screenshot that produced the finding',
      'All five remedy kinds drawn, with ours plainly labelled as ours',
      'Self-fix shows the actual change and a re-check control with a believable result state',
      'The no_solution case is designed too — what a person sees when there is no good answer yet',
    ],
    verify: 'pnpm -F prototype test:e2e -- finding-detail',
  },
  {
    id: 'X-06', stream: 'X', phase: 0, est: 'M', depends: ['X-04'],
    title: 'Questions, one at a time',
    goal: 'Yes / No / Check it for me — and the visible unlock that follows each answer.',
    acceptance: [
      'Never more than one question on screen',
      'Answering visibly adds to the timeline and opens something new',
      '"Check it for me" has its own designed waiting and result states',
      'The accounting-firm-and-Microsoft example from the concept document is one of the drawn questions',
    ],
    verify: 'pnpm -F prototype test:e2e -- questions',
  },
  {
    id: 'X-07', stream: 'X', phase: 0, est: 'M', depends: ['X-04'],
    title: 'Colleague branches and invitations',
    goal: 'The four role task lists and the invitation that arrives from a colleague, not from us.',
    acceptance: [
      'Marketing, IT, HR and Finance lists drawn, each under six items',
      'What the invited person lands on before any account exists',
      'Shared progress view, and the owner view showing who has not finished',
      '"I do not know, check for me" present on every item',
    ],
    verify: 'pnpm -F prototype test:e2e -- colleagues',
  },
  {
    id: 'X-08', stream: 'X', phase: 0, est: 'M', depends: ['X-02'],
    title: 'Supply chain, artefacts and the trust page',
    goal: 'The three things a customer forwards to someone else.',
    acceptance: [
      'Supply-chain map at three levels, legible and exportable-looking',
      'Generated artefact preview with the sign-off step drawn',
      'Public trust page, worded as dated work in progress and never as approval',
      'The share sheet: inward, upward, outward, each with its own designed target',
    ],
    verify: 'pnpm -F prototype test:e2e -- artefacts',
    notes: 'Read the claim-discipline rules before writing any copy here. The trust page is the screen most likely to be mistaken for a seal.',
  },
  {
    id: 'X-09', stream: 'X', phase: 0, est: 'S', depends: ['X-04'],
    title: 'Internal screens',
    goal: 'What we see: the consultant opening a case already briefed, and the commercial queue.',
    acceptance: [
      'Consultant view is the same case with a generated brief, and shows the customer that we looked',
      'Commercial queue ranked and explainable per row',
      'Nothing here is hidden from the customer — that rule is visible in the design itself',
    ],
    verify: 'pnpm -F prototype test:e2e -- internal',
  },
  {
    id: 'X-10', stream: 'X', phase: 0, est: 'S', depends: ['X-03', 'X-05', 'X-06', 'X-07', 'X-08', 'X-09'],
    title: 'Clickthrough assembly and review with Frits',
    goal: 'One deployed link, one guided path through every screen, and a decision.',
    acceptance: [
      'A single URL walks the whole story end to end with no dead ends',
      'Every screen reachable in under three clicks from a prototype index',
      'Review session held; feedback captured as new X tasks and resolved',
      'Frits signs off explicitly, and the sign-off is recorded in this task file',
    ],
    verify: 'manual — recorded sign-off in this file',
    notes: 'THE GATE. Nothing in phase 1 or later starts until this is done. Every downstream task depends on it through F-01.',
  },

  // ---------------------------------------------------------------- PHASE 1
  {
    id: 'F-01', stream: 'F', phase: 1, est: 'M', depends: ['X-10'],
    title: 'Monorepo scaffold and toolchain',
    goal: 'pnpm workspace, TypeScript strict, ESLint, Prettier, Vitest, and a CI workflow that runs on every push.',
    acceptance: [
      'pnpm install works from a clean clone on Linux and Windows',
      'tsconfig uses strict:true, noUncheckedIndexedAccess:true, and project references across packages',
      'A deliberately failing test fails CI; removing it makes CI green',
      'Layout matches PLAN.md §Repo layout exactly — later tasks assume those paths',
    ],
    verify: 'pnpm install && pnpm -r typecheck && pnpm test:unit',
    notes: 'No app code in this task. The only deliverable is that the harness runs.',
  },
  {
    id: 'F-02', stream: 'F', phase: 1, est: 'M', depends: ['F-01'],
    title: 'Postgres + pgvector, Drizzle, migration harness',
    goal: 'docker-compose brings up Postgres 16 with pgvector; Drizzle migrations apply and roll back; tests get a disposable schema per run.',
    acceptance: [
      'docker compose up -d gives a working database with the vector extension enabled',
      'pnpm db:migrate is idempotent; running it twice is a no-op',
      'Each vitest integration file gets an isolated schema, dropped afterwards, so tests can run in parallel',
      'No test ever touches a developer database by default — the connection string must be explicit',
    ],
    verify: 'pnpm db:migrate && pnpm test:integration -- db',
  },
  {
    id: 'F-03', stream: 'F', phase: 1, est: 'L', depends: ['F-02'],
    title: 'Core relational schema',
    goal: 'Tables for tenants, cases, case_events, findings, evidence, remedies, vendors, processing_activities, answers, jurisdictions.',
    acceptance: [
      'Every table carries tenant_id; every row carries created_at and a source reference',
      'case_events is append-only — an UPDATE or DELETE against it raises',
      'findings.remedy_id is NOT NULL: a finding without a remedy cannot be inserted (see R-02)',
      'evidence rows are immutable and content-addressed by hash',
      'Schema diagram committed to docs/schema.md, generated not hand-drawn',
    ],
    verify: 'pnpm test:integration -- schema',
    notes: 'This is the spine. Get the append-only and NOT NULL constraints in now — retrofitting them means a data migration.',
  },
  {
    id: 'F-04', stream: 'F', phase: 1, est: 'M', depends: ['F-01'],
    title: 'Shared contracts package (@gc/contracts)',
    goal: 'Zod schemas for Finding, Evidence, Remedy, Case, CaseEvent, Vendor, Duty, PlannerTask, VerifierVerdict. One definition, used by runtime validation and tests alike.',
    acceptance: [
      'Every LLM-facing input and output has a Zod schema here and nowhere else',
      'JSON Schema is generated from Zod for prompt-side structured output',
      'Finding requires: stable id, jurisdiction-scoped bindings, evidence ref, severity, remedy ref',
      'Types are exported; no package redefines these shapes locally',
    ],
    verify: 'pnpm -F @gc/contracts test',
  },
  {
    id: 'F-05', stream: 'F', phase: 1, est: 'M', depends: ['F-03'],
    title: 'Multi-tenancy isolation, provable',
    goal: 'Postgres row-level security plus a per-request tenant context, and a test suite that tries hard to break it.',
    acceptance: [
      'RLS policies on every tenant-scoped table, enabled by default and FORCEd for the app role',
      'A query without tenant context returns zero rows rather than all rows',
      'Test suite attempts cross-tenant read, write, join and aggregate — all must fail',
      'A new table without an RLS policy fails a lint check in CI',
    ],
    verify: 'pnpm test:integration -- tenancy',
    notes: 'This is one of the two things PLAN.md says cannot be retro-fitted. Do it before any feature code.',
  },
  {
    id: 'F-06', stream: 'F', phase: 1, est: 'M', depends: ['F-02'],
    title: 'Durable job queue and resumability',
    goal: 'pg-boss on the same Postgres, typed job definitions, and proof that a killed worker resumes without losing or duplicating work.',
    acceptance: [
      'Jobs are declared with a Zod payload schema and fail fast on malformed input',
      'A test kills a worker mid-job and asserts the job completes exactly once on restart',
      'Long jobs checkpoint progress so a scan surviving a restart does not begin again from zero',
      'Dead-letter queue with a visible reason string',
    ],
    verify: 'pnpm test:integration -- queue',
    notes: 'pg-boss over Temporal deliberately — see PLAN.md §Decisions. Keep the job interface narrow so swapping later is contained.',
  },
  {
    id: 'F-07', stream: 'F', phase: 1, est: 'L', depends: ['F-01'],
    title: 'Fixture site infrastructure',
    goal: 'A static server that serves deliberately broken websites from fixtures/sites/<name>/, each with an expected.json naming exactly which findings must and must not be produced.',
    acceptance: [
      'Fixture sites are plain HTML/JS with no build step and no network egress',
      'Third-party requests are simulated by local hosts mapped through the browser proxy, so no fixture ever reaches the real internet',
      'expected.json format is documented and validated by a Zod schema',
      'One reference fixture ships with this task and its expectation passes end to end',
    ],
    verify: 'pnpm test:integration -- fixtures',
    notes: 'Everything in stream S depends on this. It is the ground truth that makes a compliance scanner testable at all.',
  },
  {
    id: 'F-08', stream: 'F', phase: 1, est: 'M', depends: ['F-01'],
    title: 'Test harness: projects, gates, reporting',
    goal: 'Vitest split into unit / integration / e2e / evals / adversarial, each runnable alone, all runnable together, with coverage thresholds that fail the build.',
    acceptance: [
      'pnpm test:unit runs in under 30 seconds with no database and no network',
      'Coverage floor of 85% on packages/findings, packages/rules and packages/remedies; the rest 70%',
      'A junit report and an HTML report land in artifacts/ for CI',
      'Suites are tagged so the delivery gate (O-05) can require specific ones',
    ],
    verify: 'pnpm test:unit && pnpm test:coverage:check',
  },
  {
    id: 'F-09', stream: 'F', phase: 1, est: 'M', depends: ['F-07'],
    title: 'Network record and replay',
    goal: 'Every outbound HTTP, DNS and registry call goes through a recorder; CI replays cassettes and blocks live egress entirely.',
    acceptance: [
      'A CI run with the network cable pulled still passes the whole suite',
      'Cassettes are committed, human-readable, and redacted of anything resembling a credential',
      'A missing cassette in CI is a hard error, never a silent live call',
      'Re-recording is one documented command',
    ],
    verify: 'GC_NETWORK=replay pnpm test:integration',
    notes: 'Without this the suite is flaky and nobody trusts it, which defeats the whole point of the user not testing manually.',
  },
  {
    id: 'F-10', stream: 'F', phase: 1, est: 'S', depends: ['F-01'],
    title: 'Config, secrets and the EU-only constraint',
    goal: 'Typed config loading with startup validation, and an explicit allowlist of external endpoints the system may ever contact.',
    acceptance: [
      'Missing or malformed config fails at boot with a readable message, never at first use',
      'Every outbound host is declared in config with a purpose and a jurisdiction',
      'A test asserts no code path can reach a host outside the allowlist',
      'Model endpoints are configured as OpenAI-compatible base URLs so the self-hosted stack drops in',
    ],
    verify: 'pnpm test:unit -- config',
  },

  // ---------------------------------------------------------------- PHASE 2
  {
    id: 'S-01', stream: 'S', phase: 2, est: 'M', depends: ['F-07', 'F-09'],
    title: 'Browser pool with clean-profile isolation',
    goal: 'Playwright Chromium pool where every pass gets a genuinely fresh profile — no cookies, no storage, no service workers, no cache carried across passes.',
    acceptance: [
      'A test proves pass N cannot observe any state written during pass N-1',
      'Concurrency limit, per-page timeout, and hard kill on hang',
      'Realistic viewport, locale and timezone, configurable per scan target',
      'Memory stays flat across 200 sequential scans',
    ],
    verify: 'pnpm test:integration -- browser-pool',
    notes: 'Profile bleed silently invalidates the entire three-pass diff. Prove isolation before building on it.',
  },
  {
    id: 'S-02', stream: 'S', phase: 2, est: 'M', depends: ['S-01'],
    title: 'Pass A collector',
    goal: 'Load, wait for network quiet, touch nothing. Capture every request, every cookie, localStorage and sessionStorage writes, and a full-page screenshot.',
    acceptance: [
      'Requests captured with initiator chain, timing and resource type',
      'Cookies captured with domain, expiry, secure, httpOnly and sameSite',
      'Network-quiet heuristic documented and tested against a fixture that lazy-loads a tracker after 4 seconds',
      'Evidence written content-addressed, referenced by hash from findings',
    ],
    verify: 'pnpm test:integration -- pass-a',
  },
  {
    id: 'S-03', stream: 'S', phase: 2, est: 'L', depends: ['S-02'],
    title: 'Consent banner detection and refusal-path automation',
    goal: 'Find the banner, identify the platform where recognisable, and click through to a genuine refusal however many layers deep it is buried.',
    acceptance: [
      'Handles the top consent platforms by signature, plus a generic heuristic fallback',
      'Follows multi-layer refusal: settings, then toggles off, then save',
      'Records the click path taken as evidence, including a screenshot per step',
      'Reports honestly when it cannot find a refusal path rather than guessing — that itself is a finding',
      'Passes against at least 8 banner fixtures covering different patterns',
    ],
    verify: 'pnpm test:integration -- banner',
    notes: 'The hardest task in phase 2 and the one the whole wedge rests on. Budget accordingly. When uncertain, prefer "could not determine" over a false pass.',
  },
  {
    id: 'S-04', stream: 'S', phase: 2, est: 'M', depends: ['S-03'],
    title: 'Pass B and Pass C collectors',
    goal: 'Reject-everything and accept-everything passes producing the same shape of capture as Pass A.',
    acceptance: [
      'Pass B asserts that a refusal was actually registered, not merely clicked',
      'Pass C records the full permitted vendor set — this is the inventory later phases consume',
      'A stated choice is re-checked after reload; a banner that forgets is a finding',
      'All three passes run concurrently where safe and complete inside the performance budget',
    ],
    verify: 'pnpm test:integration -- pass-bc',
  },
  {
    id: 'S-05', stream: 'S', phase: 2, est: 'M', depends: ['S-04'],
    title: 'Three-pass differ',
    goal: 'Diff the three captures into the consent findings — the wedge itself.',
    acceptance: [
      'CNS-01 fires when non-essential requests occur before any interaction',
      'CNS-02 fires when the reject-all set is materially the same as the accept-all set, reporting the exact overlapping hosts',
      'CNS-03..08 cover missing reject on first layer, pre-ticked toggles, choice not persisted, and refusal path deeper than two layers',
      'Every finding names the specific hosts and carries the diff as evidence',
      'False-positive check: a correctly-behaving fixture produces zero consent findings',
    ],
    verify: 'pnpm test:unit -- differ && pnpm test:integration -- consent-findings',
    notes: 'The last acceptance line matters most. A scanner that cries wolf on a compliant site is worse than no scanner.',
  },
  {
    id: 'S-06', stream: 'S', phase: 2, est: 'S', depends: ['S-02'],
    title: 'Cookie classification',
    goal: 'Classify observed cookies by purpose against a maintained open database, with an explicit unknown bucket.',
    acceptance: [
      'Unknown cookies are reported as unknown, never guessed into a category',
      'Classification source and version recorded on every classification',
      'Database refresh is a scheduled job, not a build-time snapshot',
    ],
    verify: 'pnpm test:unit -- cookie-classify',
  },
  {
    id: 'S-07', stream: 'S', phase: 2, est: 'L', depends: ['S-02'],
    title: 'Host to legal entity resolution',
    goal: 'Resolve third-party hosts to named legal entities, their place of establishment and their ultimate corporate parent.',
    acceptance: [
      'Curated vendor registry with provenance on every entry, versioned in the repo',
      'Distinguishes the contracting EU entity from the ultimate parent — the distinction the whole transfer analysis rests on',
      'Unresolved hosts surface as unresolved with the raw host shown, never silently dropped',
      'Registry entries carry a review date; stale entries warn in CI',
    ],
    verify: 'pnpm test:unit -- vendor-resolve',
  },
  {
    id: 'S-08', stream: 'S', phase: 2, est: 'M', depends: ['S-07'],
    title: 'Transfer and jurisdiction determination',
    goal: 'For each resolved recipient, determine EEA status, parent jurisdiction, and whether the scanned policy names a Chapter V basis.',
    acceptance: [
      'Outputs a factual statement about corporate jurisdiction, never a legality verdict about a named company (see O-03)',
      'Data Privacy Framework participation checked against the official list with a recorded lookup date',
      'Distinguishes "hosted in the EU" from "controlled by a non-EU parent" in the finding text',
    ],
    verify: 'pnpm test:unit -- transfers',
  },
  {
    id: 'S-09', stream: 'S', phase: 2, est: 'M', depends: ['S-01'],
    title: 'Policy discovery and fetch',
    goal: 'Locate the privacy policy, cookie policy and terms across common link patterns, footers, and language variants.',
    acceptance: [
      'Finds the policy on at least 9 of 10 canary sites',
      'Handles multi-page policies and per-language variants',
      'Records the URL, fetch time and a content hash as evidence',
      'A site with no discoverable policy is itself a finding',
    ],
    verify: 'pnpm test:integration -- policy-discovery',
  },
  {
    id: 'S-10', stream: 'S', phase: 2, est: 'L', depends: ['S-09', 'A-07'],
    title: 'Article 13/14 clause analysis',
    goal: 'Test the policy clause by clause against the disclosure requirements, with every result carrying the sentence it was drawn from or an explicit not-found.',
    acceptance: [
      'Model output conforms to the Zod schema in @gc/contracts or the run fails',
      'Every positive result quotes source text that is verifiably present in the fetched document — checked by exact substring match, not by the model',
      'Every legal citation resolves to a real paragraph in the corpus for the target jurisdiction',
      'Ambiguous clauses return not-determined rather than a guess',
      'Runs against 12 policy fixtures with known-correct expectations, ≥95% agreement',
    ],
    verify: 'pnpm test:evals -- policy-clauses',
    notes: 'This is the first task where a model asserts something a customer will read. It goes through the verifier gate (A-07) — hence the dependency.',
  },
  {
    id: 'S-11', stream: 'S', phase: 2, est: 'M', depends: ['S-02'],
    title: 'Form inventory and consent patterns',
    goal: 'Enumerate every form, its fields, its destination, whether a notice sits at the point of collection, and whether opt-in is bundled or pre-ticked.',
    acceptance: [
      'Detects pre-ticked consent boxes including CSS-hidden and JS-set states',
      'Flags bundled consent where one checkbox covers marketing and terms together',
      'Classifies field sensitivity so a form asking for health or financial data raises severity',
      'Never submits a form — read-only inspection only',
    ],
    verify: 'pnpm test:integration -- forms',
  },
  {
    id: 'S-12', stream: 'S', phase: 2, est: 'M', depends: ['S-01'],
    title: 'Security surface checks',
    goal: 'The Article 32 surface a stranger can see: TLS, HSTS, headers, mixed content, downgrade on form posts, referrer leakage, exposed paths.',
    acceptance: [
      'Exposed-path probing is limited to a documented, conservative list and respects robots directives',
      'Never attempts authentication, never sends a payload, never enumerates users beyond what a single public endpoint returns',
      'Each check maps to a finding with a remedy that is a concrete config change',
    ],
    verify: 'pnpm test:integration -- security-surface',
  },
  {
    id: 'S-13', stream: 'S', phase: 2, est: 'M', depends: ['S-02'],
    title: 'Session replay and fingerprinting detection',
    goal: 'Detect replay and heatmap tools and, where observable, whether input masking is off on pages containing sensitive fields.',
    acceptance: [
      'Detects the major replay vendors by network signature and by API surface on the page',
      'Reports specifically when replay is active on a page carrying payment or account fields',
      'Canvas, font and audio fingerprinting probes detected and reported separately',
    ],
    verify: 'pnpm test:integration -- replay-detect',
  },
  {
    id: 'S-14', stream: 'S', phase: 2, est: 'M', depends: ['S-05', 'R-01'],
    title: 'Finding assembly and severity',
    goal: 'Assemble detector output into persisted findings with severity, evidence references, jurisdiction bindings and a resolved remedy.',
    acceptance: [
      'Severity is computed from a documented rule table, not chosen ad hoc per detector',
      'Assembly refuses to persist a finding lacking evidence or a remedy',
      'Identical scans produce byte-identical finding sets — determinism is asserted in a test',
      'Findings carry a stable id so the same problem is recognisable across re-scans',
    ],
    verify: 'pnpm test:integration -- finding-assembly',
  },
  {
    id: 'S-15', stream: 'S', phase: 2, est: 'L', depends: ['S-14', 'T-01'],
    title: 'The twenty launch finding types',
    goal: 'Twenty finding types complete: detector, fixture, expectation, severity, jurisdiction bindings, remedy, and guide content in English and Danish.',
    acceptance: [
      'Each of the twenty has a passing fixture and a passing negative fixture',
      'Each has a remedy of a declared kind and a guide page that a non-technical reader can follow',
      'The set covers consent, recipients, transfers, notice, collection, observation and security',
      'docs/findings.md lists all twenty with their bindings, generated from the registry',
    ],
    verify: 'pnpm test:integration -- findings-catalogue && pnpm run check:finding-completeness',
    notes: 'Twenty done properly beats sixty done badly. Resist scope growth here; new types are cheap once the shape is right.',
  },

  // ---------------------------------------------------------------- REMEDIES
  {
    id: 'R-01', stream: 'R', phase: 2, est: 'M', depends: ['F-04'],
    title: 'Remedy schema and catalogue store',
    goal: 'Remedies as first-class content: kind, jurisdiction scope, effort, the actual instruction, and what closes the finding.',
    acceptance: [
      'Kinds are exactly: self_fix, generated_artefact, our_product, partner_alternative, no_solution',
      'Remedies are jurisdiction-scoped and locale-scoped like findings',
      'Each remedy declares a verification method so "did this actually fix it" is machine-checkable',
      'Catalogue is versioned; a remedy change is auditable',
    ],
    verify: 'pnpm test:unit -- remedy-schema',
  },
  {
    id: 'R-02', stream: 'R', phase: 2, est: 'S', depends: ['R-01', 'F-03'],
    title: 'Enforce: no finding without a remedy',
    goal: 'Make the product rule a structural impossibility rather than a guideline — database constraint, type-level requirement and a CI check.',
    acceptance: [
      'NOT NULL foreign key from findings to remedies in the database',
      'The Finding type cannot be constructed without a remedy reference',
      'CI check enumerates every registered detector and fails if any lacks a remedy in every supported jurisdiction',
      'The no_solution kind satisfies the constraint and writes to the demand ledger',
    ],
    verify: 'pnpm run check:finding-completeness',
    notes: 'Small task, load-bearing. This is the sentence from the concept doc turned into a constraint.',
  },
  {
    id: 'R-03', stream: 'R', phase: 2, est: 'L', depends: ['R-01'],
    title: 'Twenty remedy guides, English and Danish',
    goal: 'Real content for each launch finding: what is wrong, why it matters, exactly what to change, and how to confirm it worked.',
    acceptance: [
      'Written for a competent non-specialist; no unexplained jargon',
      'Every code or config snippet is tested against a fixture that starts broken and ends fixed',
      'Danish is a translation of a structured content object, not a separate document',
      'Each guide is a standalone page that stands up as a search landing page',
    ],
    verify: 'pnpm test:integration -- guides && pnpm run check:guide-snippets',
  },
  {
    id: 'R-04', stream: 'R', phase: 2, est: 'M', depends: ['R-01'],
    title: 'Remedy resolver and solution catalogue',
    goal: 'Given a finding and a context, pick the cheapest remedy that genuinely closes it, honestly.',
    acceptance: [
      'A free self-service fix always outranks a paid one when both would close the finding',
      'Anything of ours is flagged as ours in the returned object, not only in the UI',
      'partner_alternative returns at least two options or degrades to no_solution',
      'Resolution is deterministic and explained — the reason is stored, not just the choice',
    ],
    verify: 'pnpm test:unit -- remedy-resolver',
    notes: 'The honesty rules from the concept doc live here as tests, so they cannot quietly erode later.',
  },
  {
    id: 'R-05', stream: 'R', phase: 2, est: 'M', depends: ['R-04'],
    title: 'Demand ledger',
    goal: 'Every no_solution outcome recorded with sector, size, country and cause; aggregated into a ranked view.',
    acceptance: [
      'Write path runs from the first scan onward, before the ledger is interesting',
      'Aggregation is anonymised at read time; no single company is identifiable in the ranked view',
      'Retention and purpose for ledger data documented before the first row lands',
      'A ranked report is exportable as CSV and as a page',
    ],
    verify: 'pnpm test:integration -- demand-ledger',
  },

  // ---------------------------------------------------------------- CASE
  {
    id: 'C-01', stream: 'C', phase: 3, est: 'M', depends: ['F-03'],
    title: 'Case object, numbering and ownership',
    goal: 'A case opens on first scan with a human-quotable number, no account required, claimable later by email.',
    acceptance: [
      'Number format is CC-YY-XXXX with a country prefix, collision-free, and readable aloud without ambiguity',
      'An unclaimed case is reachable only by its unguessable URL and expires if never claimed',
      'Claiming requires proving control of an email address at the scanned domain, or an explicit override path',
      'Two scans of the same domain by the same owner continue one case rather than opening a second',
    ],
    verify: 'pnpm test:integration -- case-lifecycle',
  },
  {
    id: 'C-02', stream: 'C', phase: 3, est: 'M', depends: ['C-01'],
    title: 'Timeline events',
    goal: 'Append-only, dated record of every scan, answer, fix, verification, join and generated document.',
    acceptance: [
      'Events are immutable and ordered; no path in the codebase can rewrite one',
      'Every event names its actor — a person, an agent, or the watcher',
      'The timeline renders as the accountability record referenced in the concept doc, exportable as dated PDF',
      'Event types are a closed enum in @gc/contracts',
    ],
    verify: 'pnpm test:integration -- timeline',
  },
  {
    id: 'C-03', stream: 'C', phase: 3, est: 'S', depends: ['C-02'],
    title: 'Case state machine',
    goal: 'opened → assessed → working → documented → watched, with explicit transitions and no way to skip backwards silently.',
    acceptance: [
      'Transitions are declared in one place and tested exhaustively',
      'State is derived from evidence, not set by hand — reaching documented requires the artefacts to exist',
      'A case never reaches a terminal state; watched is the resting state',
    ],
    verify: 'pnpm test:unit -- case-state',
  },
  {
    id: 'C-04', stream: 'C', phase: 3, est: 'M', depends: ['C-02'],
    title: 'Export and delete — proving the case is theirs',
    goal: 'One-click full export and one-click hard delete, both demonstrable.',
    acceptance: [
      'Export includes findings, evidence, timeline, answers and generated documents in an openable format',
      'Delete removes evidence blobs as well as rows, and a test asserts nothing survives except an anonymous deletion audit stub',
      'Both operations complete inside a documented time bound and are themselves timeline events',
      'The case page states plainly, in the interface, what is collected and who can see it',
    ],
    verify: 'pnpm test:integration -- case-export-delete',
    notes: 'The concept doc names this as the guardrail that protects the whole case idea. Treat the copy on the page as part of the deliverable.',
  },
  {
    id: 'C-05', stream: 'C', phase: 3, est: 'M', depends: ['C-03', 'S-14'],
    title: 'Re-scan and fix verification loop',
    goal: 'Press re-check on one finding, re-run only what is needed, and close it if the evidence now says so.',
    acceptance: [
      'Targeted re-verification of a single finding costs a fraction of a full scan',
      'A closed finding that regresses reopens with both dates on the timeline',
      'Verification uses the remedy verification method declared in R-01',
      'Weekly watch job diffs against the last run and raises only genuine changes',
    ],
    verify: 'pnpm test:integration -- reverify',
  },

  // ---------------------------------------------------------------- WEB
  {
    id: 'U-01', stream: 'U', phase: 2, est: 'M', depends: ['F-01'],
    title: 'Next.js app shell, tokens, locale routing',
    goal: 'App router, design tokens matching the concept document, locale-prefixed routes, dark and light themes.',
    acceptance: [
      'Locale is a route segment from the first commit; no hardcoded strings anywhere in components',
      'Both themes defined at token level and asserted by a visual test',
      'Server-rendered by default — the guide pages are an SEO surface',
      'Lighthouse accessibility ≥ 95 on the shell',
    ],
    verify: 'pnpm test:e2e -- shell',
  },
  {
    id: 'U-02', stream: 'U', phase: 2, est: 'M', depends: ['U-01', 'S-05'],
    title: 'The front door',
    goal: 'One field, one button, no account — and honest progress while the three passes run.',
    acceptance: [
      'A scan can be started with keyboard only, and the field validates a domain without being precious about format',
      'Progress streams real stages, never a fake spinner with invented percentages',
      'Abuse controls: rate limit per source, queue depth cap, and a polite refusal message',
      'Works on a phone, because half of first visits will be on one',
    ],
    verify: 'pnpm test:e2e -- front-door',
  },
  {
    id: 'U-03', stream: 'U', phase: 3, est: 'L', depends: ['U-02', 'C-02'],
    title: 'The case page',
    goal: 'Case number, progress track, timeline, findings with evidence drawers, and the remedy buttons.',
    acceptance: [
      'No score in the header — fixes-ready count and progress track, per the concept document',
      'Every finding can be expanded to the raw evidence that produced it',
      'Severity is encoded in form as well as colour so it survives colour-blindness and greyscale printing',
      'The page is legible printed, because it will be printed',
    ],
    verify: 'pnpm test:e2e -- case-page',
  },
  {
    id: 'U-04', stream: 'U', phase: 3, est: 'M', depends: ['U-03', 'R-04'],
    title: 'Remedy interactions',
    goal: 'Every finding ends in a control that does something, with a visible result.',
    acceptance: [
      'Self-fix shows the exact change and a re-check button that reports honestly',
      'Generated artefacts preview before they are published anywhere',
      'Our products are labelled as ours in the interface, plainly',
      'Nothing silently navigates away from the case',
    ],
    verify: 'pnpm test:e2e -- remedies',
  },
  {
    id: 'U-05', stream: 'U', phase: 3, est: 'M', depends: ['U-03'],
    title: 'Public trust page',
    goal: 'An opt-in public page a company links from its own site, showing dated progress without overclaiming.',
    acceptance: [
      'Off by default; publishing is an explicit, reversible act recorded on the timeline',
      'Wording is "work in progress, dated" and never implies certification or approval',
      'Shows what has been fixed and when, never the open findings, which are theirs alone',
      'Carries a scan-your-own-domain call to action — this is the growth loop',
    ],
    verify: 'pnpm test:e2e -- trust-page',
    notes: 'Read O-03 before writing the copy. This page is the artefact most likely to be mistaken for a seal.',
  },
  {
    id: 'U-06', stream: 'U', phase: 2, est: 'M', depends: ['U-01', 'R-03'],
    title: 'Guide pages',
    goal: 'One page per finding type per locale, generated from the remedy content, built to be found.',
    acceptance: [
      'Static generation with correct metadata, canonical URLs and hreflang across locales',
      'Each page ends in a scan entry point',
      'Content comes from the remedy catalogue; there is no second copy of the text',
    ],
    verify: 'pnpm test:e2e -- guides',
  },
  {
    id: 'U-07', stream: 'U', phase: 3, est: 'M', depends: ['U-03', 'P-02'],
    title: 'Share flows',
    goal: 'Inward to colleagues, upward as a one-screen summary, outward as the trust page.',
    acceptance: [
      'Inward invitations come from the colleague, in their name, and land on a scoped view',
      'The upward view fits one screen and shows progress, not a grade',
      'Every share is a timeline event and every share is revocable',
    ],
    verify: 'pnpm test:e2e -- sharing',
  },
  {
    id: 'U-08', stream: 'U', phase: 6, est: 'M', depends: ['U-03', 'U-05'],
    title: 'Accessibility, responsive and print pass',
    goal: 'The whole surface audited rather than the shell alone.',
    acceptance: [
      'Automated axe pass with zero serious or critical issues on every route',
      'Keyboard-only completion of a full journey: scan, read, fix, re-check',
      'Reduced-motion respected; nothing conveys meaning by colour alone',
      'Case page and evidence print correctly to A4',
    ],
    verify: 'pnpm test:e2e -- a11y',
  },

  // ---------------------------------------------------------------- DEEP
  {
    id: 'D-01', stream: 'D', phase: 4, est: 'M', depends: ['F-09'],
    title: 'DNS, TXT, SPF and MX collection',
    goal: 'Resolve the records and map verification tokens and SPF includes to named services.',
    acceptance: [
      'Token-to-service map is curated, versioned and provenance-tracked like the vendor registry',
      'Unknown tokens are reported as unknown with the raw value',
      'Every mapped service becomes a candidate processor on the case graph',
    ],
    verify: 'pnpm test:integration -- dns-collect',
  },
  {
    id: 'D-02', stream: 'D', phase: 4, est: 'S', depends: ['D-01'],
    title: 'Certificate transparency enumeration',
    goal: 'Enumerate subdomains from public logs and classify what they suggest.',
    acceptance: [
      'Enumeration only; no probing of discovered hosts beyond a single safe HEAD',
      'Findings describe exposure risk without asserting a breach',
      'Results capped and rate-limited so a large estate cannot stall a scan',
    ],
    verify: 'pnpm test:integration -- ct-enum',
  },
  {
    id: 'D-03', stream: 'D', phase: 4, est: 'L', depends: ['F-09'],
    title: 'Business registry adapters',
    goal: 'One interface, Danish and German implementations, returning entity, sector, headcount band and group structure.',
    acceptance: [
      'Adapter interface is stable enough that a third country needs no changes outside its own file',
      'Rate limits and terms of each registry respected and documented in the adapter',
      'Missing data returns unknown; the pipeline never guesses a headcount',
      'A contract test suite runs against every adapter identically',
    ],
    verify: 'pnpm test:integration -- registry-adapters',
  },
  {
    id: 'D-04', stream: 'D', phase: 4, est: 'M', depends: ['D-03'],
    title: 'Job advert stack extraction',
    goal: 'Find current adverts and extract named tools into candidate processors.',
    acceptance: [
      'Only public listings; nothing behind a login',
      'Extraction is conservative — a tool is only claimed when named explicitly',
      'Each extracted tool carries the advert URL and date as evidence',
    ],
    verify: 'pnpm test:evals -- job-extraction',
  },
  {
    id: 'D-05', stream: 'D', phase: 4, est: 'M', depends: ['D-01'],
    title: 'App listing and data-safety comparison',
    goal: 'Find the mobile app if any, read its declared data collection, compare against the website policy.',
    acceptance: [
      'Contradictions between store declaration and website policy produce a finding quoting both',
      'Absence of an app is a clean negative, not an error',
    ],
    verify: 'pnpm test:integration -- app-listing',
  },
  {
    id: 'D-06', stream: 'D', phase: 4, est: 'L', depends: ['S-09', 'A-07'],
    title: 'Processing agreement discovery and Article 28 analysis',
    goal: 'Find their DPA, and test it against what Article 28(3) actually requires.',
    acceptance: [
      'Distinguishes no agreement, an unfindable agreement, and an inadequate agreement — three different findings with three different remedies',
      'Each required element checked individually with quoted source or explicit absence',
      'Breach notification window, sub-processor objection mechanism and transfer annexes checked specifically',
      'Runs through the verifier gate; every legal claim carries a resolving citation',
      'Evaluated against 10 real-world agreement fixtures with expert-labelled expectations',
    ],
    verify: 'pnpm test:evals -- dpa-analysis',
    notes: 'The highest-value thread in the concept document. Accuracy matters more than coverage — a wrong reading here is quoted back at you.',
  },
  {
    id: 'D-07', stream: 'D', phase: 4, est: 'L', depends: ['D-06'],
    title: 'Sub-processor extraction and recursion',
    goal: 'Extract their sub-processor list, then follow each named vendor to its own list, depth-limited.',
    acceptance: [
      'Depth cap of 3 and a hard node cap, both configurable and both enforced by test',
      'Cycle detection — vendors do reference each other',
      'Every edge carries the document and date it came from',
      'Politeness: one request per host per interval, honouring robots directives',
    ],
    verify: 'pnpm test:integration -- subprocessor-recursion',
  },
  {
    id: 'D-08', stream: 'D', phase: 4, est: 'M', depends: ['D-07'],
    title: 'Supply-chain map',
    goal: 'The diagram the customer has never seen, exportable and shareable.',
    acceptance: [
      'Renders legibly at 3 levels and 60 nodes without becoming spaghetti',
      'Nodes carry jurisdiction and the evidence link that placed them there',
      'Exports to PNG and PDF; readable in greyscale',
    ],
    verify: 'pnpm test:e2e -- supply-chain-map',
  },
  {
    id: 'D-09', stream: 'D', phase: 4, est: 'M', depends: ['D-03', 'A-02'],
    title: 'Sector inference and question selection',
    goal: 'Narrow two hundred possible questions to the handful whose answers actually branch the assessment.',
    acceptance: [
      'Question selection is driven by the rules engine, not by the model',
      'Each candidate question declares which duties its answer would resolve',
      'Selection is explainable — the case can show why it asked what it asked',
      'Never asks something already derivable from evidence already held',
    ],
    verify: 'pnpm test:unit -- question-selection',
  },
  {
    id: 'D-10', stream: 'D', phase: 4, est: 'M', depends: ['D-09', 'U-03'],
    title: 'One question at a time',
    goal: 'Yes / No / Check it for me — one tap, and visible progress on the case for each answer.',
    acceptance: [
      '"Check it for me" enqueues an agent task and returns immediately',
      'Each answer lands on the timeline and visibly unlocks something',
      'No screen ever shows more than one question',
      'Answers are attributable and revisable, with both versions kept',
    ],
    verify: 'pnpm test:e2e -- questions',
  },
  {
    id: 'D-11', stream: 'D', phase: 4, est: 'M', depends: ['D-07'],
    title: 'Crawl etiquette and scan authorisation',
    goal: 'Rate limits, honest bot identity, published behaviour, and a rule about who may run a deep scan on whom.',
    acceptance: [
      'Named user agent with a URL explaining exactly what the scanner does',
      'Per-host and per-domain rate limits enforced centrally, not per collector',
      'Deep scan of a third party requires either domain control or a documented public-interest path',
      'A published page describes the scanner behaviour, and a test asserts the code matches the page',
      'Never authenticates, never submits, never follows a link requiring consent to terms',
    ],
    verify: 'pnpm test:integration -- crawl-etiquette',
  },

  // ---------------------------------------------------------------- AGENT
  {
    id: 'A-01', stream: 'A', phase: 5, est: 'L', depends: ['F-03'],
    title: 'Case graph schema',
    goal: 'Activities, data categories, purposes, legal bases, vendors, transfers, risks, controls and evidence as typed rows with provenance.',
    acceptance: [
      'Every node and edge carries source, confidence and timestamp',
      'Derived facts are distinguishable from asserted facts and from answered facts',
      'Contradictions are representable and surfaced rather than silently resolved',
      'The register (G-01) is a pure projection of this graph',
    ],
    verify: 'pnpm test:integration -- case-graph',
  },
  {
    id: 'A-02', stream: 'A', phase: 5, est: 'L', depends: ['A-01'],
    title: 'Obligations engine and rule language',
    goal: 'Deterministic, versioned, human-authored rules mapping graph state to duties, each declaring its jurisdiction and citation.',
    acceptance: [
      'Rules are data, not code, and are reviewable by a non-programmer',
      'Evaluation is total and deterministic — same graph, same jurisdiction, same duties, always',
      'Every rule cites an article that resolves in the corpus, checked in CI',
      'A rule cannot be added without a test case and a citation',
    ],
    verify: 'pnpm test:unit -- rules-engine && pnpm run check:rule-citations',
  },
  {
    id: 'A-03', stream: 'A', phase: 5, est: 'L', depends: ['A-02', 'I-02'],
    title: 'First forty rules across two jurisdictions',
    goal: 'Enough of the rule set to produce a real duty list for a real company in Denmark and Germany.',
    acceptance: [
      'Forty rules, each with a citation, a test case and a jurisdiction scope',
      'At least six rules where Danish and German outcomes genuinely differ',
      'A golden test fixes the duty set for three synthetic companies per jurisdiction',
    ],
    verify: 'pnpm test:unit -- rules-corpus',
  },
  {
    id: 'A-04', stream: 'A', phase: 5, est: 'M', depends: ['F-06', 'F-04'],
    title: 'Typed task catalogue and dispatcher',
    goal: 'The finite vocabulary the planner may emit, each with a payload schema, a cost and an output schema.',
    acceptance: [
      'Catalogue is closed — an unknown task type is rejected at the boundary, loudly',
      'Every task declares cost so the planner can be held to a budget',
      'Dispatcher enforces per-case and per-scan budgets and stops rather than overspending',
    ],
    verify: 'pnpm test:unit -- task-catalogue',
  },
  {
    id: 'A-05', stream: 'A', phase: 5, est: 'L', depends: ['A-04'],
    title: 'Worker implementations',
    goal: 'One narrow specialist per task type: crawler, contract reader, registry adapter, researcher, drafter.',
    acceptance: [
      'Each worker has the smallest tool set that does its job and is tested in isolation',
      'The contract reader has no network access; the crawler has no corpus access',
      'Workers return claims, never conclusions — assembly and judgement happen elsewhere',
    ],
    verify: 'pnpm test:integration -- workers',
  },
  {
    id: 'A-06', stream: 'A', phase: 5, est: 'L', depends: ['A-04', 'A-02'],
    title: 'The planner',
    goal: 'Model-driven planning over the open duties, constrained to the task catalogue and to a budget.',
    acceptance: [
      'Cannot emit anything outside the catalogue; malformed plans are rejected and retried once, then escalated',
      'Explains its choice per task in a line a human can read on the case',
      'Behavioural evals: on 20 fixed scenarios it selects a sensible next task ≥ 90% of the time',
      'Deterministic replay: given the same graph and seed, plans are reproducible for debugging',
    ],
    verify: 'pnpm test:evals -- planner',
    notes: 'Ship A-05 with a hard-coded sequence first and swap this in behind it. Do not block phase 4 on the planner being good.',
  },
  {
    id: 'A-07', stream: 'A', phase: 2, est: 'L', depends: ['F-04', 'A-08'],
    title: 'The verifier gate',
    goal: 'Nothing enters the graph without an evidence pointer and, for legal claims, a citation that actually resolves.',
    acceptance: [
      'Quoted evidence is confirmed by exact substring match against the stored source, in code, not by a model',
      'Citations are resolved against the corpus for the stated jurisdiction; an unresolvable citation rejects the claim',
      'A second-pass model check runs on claims that pass the mechanical checks',
      'Rejections are recorded with a reason and are visible in an internal review queue',
      'Poisoned-input suite: 50 deliberately false or fabricated claims, ≥ 98% rejected',
    ],
    verify: 'pnpm test:evals -- verifier && pnpm test:adversarial -- claim-poisoning',
    notes: 'Scheduled in phase 2 despite being agent work, because S-10 needs it. It is the single most load-bearing safety component.',
  },
  {
    id: 'A-08', stream: 'A', phase: 2, est: 'M', depends: ['F-02'],
    title: 'Corpus retrieval with jurisdiction filter',
    goal: 'Retrieval over regulation, recitals, guidance and case law that can resolve a citation to an exact paragraph.',
    acceptance: [
      'Every corpus chunk carries jurisdiction, instrument, article and paragraph identifiers',
      'A citation string resolves to exactly one paragraph or fails — no fuzzy nearest match',
      'Retrieval can be filtered to a jurisdiction and never leaks another country as authority',
      'Corpus version is recorded on every claim so old findings stay explicable',
    ],
    verify: 'pnpm test:integration -- corpus-resolve',
  },
  {
    id: 'A-09', stream: 'A', phase: 5, est: 'M', depends: ['A-07', 'C-02'],
    title: 'Human sign-off gate',
    goal: 'Anything leaving the system carries a named signature and an audit trail.',
    acceptance: [
      'Generated artefacts cannot be published or exported without an explicit named sign-off',
      'The signature records who, when, and which version they saw',
      'Sign-off appears on the timeline and in the evidence pack',
    ],
    verify: 'pnpm test:integration -- signoff',
  },
  {
    id: 'A-10', stream: 'A', phase: 2, est: 'L', depends: ['A-07'],
    title: 'Prompt-injection defences for untrusted content',
    goal: 'Everything the scanner reads is hostile input. Treat page text, policies and contracts as data, never as instructions.',
    acceptance: [
      'Untrusted content is delimited and labelled as data in every prompt that touches it',
      'Model outputs that attempt to change scan scope, severity or verdict on instruction from scanned content are rejected',
      'The adversarial fixture suite includes sites embedding injection attempts in visible text, HTML comments, alt text, CSS content and the policy document itself',
      'A successful injection anywhere in the suite fails the build',
    ],
    verify: 'pnpm test:adversarial -- injection',
    notes: 'This product reads attacker-controlled text by design. Treat this as a security control, not a prompt-quality nicety.',
  },

  // ---------------------------------------------------------------- GENERATORS
  {
    id: 'G-01', stream: 'G', phase: 5, est: 'L', depends: ['A-01'],
    title: 'Processing register seeded from evidence',
    goal: 'Every detected vendor becomes a draft activity row with purpose, likely basis, recipient and transfer question pre-filled.',
    acceptance: [
      'Drafts are visibly drafts and require confirmation before counting as answered',
      'Each draft cites the evidence that produced it',
      'Export matches what an authority expects to receive, in the target locale',
      'Correcting a row is faster than writing one — measured on a real fixture company',
    ],
    verify: 'pnpm test:integration -- register-seed',
  },
  {
    id: 'G-02', stream: 'G', phase: 5, est: 'L', depends: ['G-01', 'A-09'],
    title: 'Privacy policy and cookie declaration generators',
    goal: 'Documents generated from the register, so they describe what is actually happening.',
    acceptance: [
      'Every statement in the output traces to a graph row; nothing is boilerplate filler',
      'Refuses to generate where the register has gaps, naming the gaps instead of inventing text',
      'Output in the target locale, legally structured for the target jurisdiction',
      'Generated documents are re-checked against the live site by G-05',
    ],
    verify: 'pnpm test:evals -- policy-generation',
  },
  {
    id: 'G-03', stream: 'G', phase: 5, est: 'M', depends: ['G-01', 'D-07'],
    title: 'DPA and sub-processor page generators',
    goal: 'The artefacts a company selling a service needs and usually lacks.',
    acceptance: [
      'Generated agreement contains every Article 28(3) element, each traceable to the requirement',
      'Sub-processor page is generated from the discovered supply chain and stays updatable',
      'Clear notice that a lawyer should review before use, in the document itself',
    ],
    verify: 'pnpm test:evals -- dpa-generation',
  },
  {
    id: 'G-04', stream: 'G', phase: 5, est: 'M', depends: ['C-02'],
    title: 'Evidence pack export',
    goal: 'A dated bundle proving the work happened — the accountability artefact.',
    acceptance: [
      'Includes timeline, findings, evidence, sign-offs and corpus versions',
      'Reproducible: the same case at the same point exports identically',
      'Opens without proprietary software',
    ],
    verify: 'pnpm test:integration -- evidence-pack',
  },
  {
    id: 'G-05', stream: 'G', phase: 5, est: 'M', depends: ['G-02', 'C-05'],
    title: 'Drift check: policy versus live site',
    goal: 'Flag when the published document no longer matches what the crawler sees.',
    acceptance: [
      'A newly added vendor not named in the policy raises a specific finding within one watch cycle',
      'Drift findings name both sides — what the policy says and what the site does',
      'No false alarms on cosmetic changes, asserted against a fixture that changes markup but not behaviour',
    ],
    verify: 'pnpm test:integration -- policy-drift',
  },

  // ---------------------------------------------------------------- PEOPLE
  {
    id: 'P-01', stream: 'P', phase: 5, est: 'M', depends: ['C-02'],
    title: 'Roles and scoped task lists',
    goal: 'Marketing, IT, HR, Finance — each sees only what they can actually change.',
    acceptance: [
      'Under six items per role, enforced by the assembler rather than by hope',
      'Scope is derived from the finding, not assigned manually',
      'Every item offers "I do not know, check for me" which routes back to the agent',
      'A role member cannot see the rest of the case unless the owner grants it',
    ],
    verify: 'pnpm test:integration -- role-lists',
  },
  {
    id: 'P-02', stream: 'P', phase: 5, est: 'M', depends: ['P-01'],
    title: 'Invitations from a colleague',
    goal: 'The invitation comes from the person, in their name, and lands directly on the work.',
    acceptance: [
      'No account creation before seeing the task list',
      'Invitation links are single-purpose, expiring and revocable',
      'Every invitation and acceptance is a timeline event',
      'Rate-limited so the feature cannot be used to send unsolicited mail',
    ],
    verify: 'pnpm test:e2e -- invitations',
  },
  {
    id: 'P-03', stream: 'P', phase: 5, est: 'S', depends: ['P-02'],
    title: 'Shared progress and chasing',
    goal: 'Everyone can see where the case stands, and the owner can see who has not finished.',
    acceptance: [
      'Progress is visible to all participants without exposing findings outside their scope',
      'Reminders are owner-initiated, never automatic vendor mail',
    ],
    verify: 'pnpm test:e2e -- shared-progress',
  },

  // ---------------------------------------------------------------- LANES
  {
    id: 'L-01', stream: 'L', phase: 4, est: 'M', depends: ['D-03'],
    title: 'Qualification signal and lane routing',
    goal: 'Score the case from public facts into the self-serve lane or the human lane.',
    acceptance: [
      'Signals: headcount band, sector, subdomain count, enterprise systems detected, multiple entities, multiple countries, regulated sector',
      'Score is explainable, stored, and never shown to the customer',
      'Lane assignment changes nothing about what the customer receives — it only decides whether a person reaches out',
      'A test asserts no feature is gated by lane',
    ],
    verify: 'pnpm test:unit -- lane-routing',
    notes: 'The last acceptance line is the rule from §08 of the concept doc. Encode it as a test so it cannot erode.',
  },
  {
    id: 'L-02', stream: 'L', phase: 5, est: 'M', depends: ['L-01', 'C-02'],
    title: 'Consultant view of the same case',
    goal: 'An internal user opens the customer case already briefed, with their access logged.',
    acceptance: [
      'Internal access is recorded on the timeline and visible to the customer',
      'No hidden internal annotations on a customer-visible object',
      'The brief is generated from the case, not written by hand',
    ],
    verify: 'pnpm test:integration -- consultant-view',
  },
  {
    id: 'L-03', stream: 'L', phase: 5, est: 'S', depends: ['L-01'],
    title: 'Commercial queue',
    goal: 'Open cases ranked by qualification, severity and how much of it we can actually solve.',
    acceptance: [
      'Ranking is explainable per row',
      'Contact happens about a finding, never about tool usage — the queue surfaces the finding to open with',
    ],
    verify: 'pnpm test:unit -- commercial-queue',
  },
  {
    id: 'L-04', stream: 'L', phase: 5, est: 'M', depends: ['U-05'],
    title: 'Referral and benchmarks',
    goal: 'Ask at the moment something goes green, and give small companies a number worth showing.',
    acceptance: [
      'Benchmark computed from the census corpus, honest about sample size',
      'Referral prompt appears on a fix confirmation and nowhere else',
      'Attribution tracked without third-party trackers, because of course',
    ],
    verify: 'pnpm test:e2e -- referral',
  },

  // ---------------------------------------------------------------- INTERNATIONAL
  {
    id: 'I-01', stream: 'I', phase: 2, est: 'M', depends: ['F-04'],
    title: 'Translatable content model',
    goal: 'Findings, remedies and guides as structured content objects with locale variants — never hardcoded strings.',
    acceptance: [
      'A missing translation falls back to English visibly, and is reported, never silently',
      'Adding a locale requires no code change outside content files',
      'A CI check lists untranslated content per locale',
    ],
    verify: 'pnpm run check:i18n-coverage',
  },
  {
    id: 'I-02', stream: 'I', phase: 2, est: 'L', depends: ['I-01', 'A-08'],
    title: 'Jurisdiction bindings',
    goal: 'A finding has one stable identity and many jurisdiction-scoped bindings: the instrument, the article, the authority, the guide text.',
    acceptance: [
      'No article number appears anywhere in detector code',
      'Resolving a finding for an unsupported jurisdiction degrades explicitly rather than falling back to Danish or German law',
      'The binding table is data and is reviewable by a lawyer without reading code',
    ],
    verify: 'pnpm test:unit -- jurisdiction-bindings',
    notes: 'This is the correction from rev. 1 of the concept doc made structural. If this task is skipped, the product becomes Danish permanently.',
  },
  {
    id: 'I-03', stream: 'I', phase: 3, est: 'S', depends: ['I-02'],
    title: 'Locale from the target, not the visitor',
    goal: 'A German site produces a German case, whoever ran the scan.',
    acceptance: [
      'Target locale inferred from site language, top-level domain and registry entry, in that order of confidence',
      'The visitor can override, and the override is remembered per case',
      'Case number prefix follows the target country',
    ],
    verify: 'pnpm test:integration -- target-locale',
  },
  {
    id: 'I-04', stream: 'I', phase: 6, est: 'M', depends: ['I-02', 'A-03'],
    title: 'Second jurisdiction end to end',
    goal: 'Prove the architecture by running the whole product for Germany, not only Denmark.',
    acceptance: [
      'A German fixture company produces German bindings, German authority references and German guide text throughout',
      'No Danish string, article or authority appears anywhere in the German output',
      'The work required is content and rules only — zero changes to detector or UI code, asserted by reviewing the diff',
    ],
    verify: 'pnpm test:integration -- jurisdiction-matrix',
  },

  // ---------------------------------------------------------------- OPS
  {
    id: 'O-01', stream: 'O', phase: 6, est: 'M', depends: ['G-01'],
    title: 'Our own compliance, published',
    goal: 'Run the product against ourselves and publish the result — case, register, supply chain, processing agreement, sub-processor list.',
    acceptance: [
      'Our own case is public and current',
      'Sub-processor list, retention schedule and deletion path exist before the first paying customer',
      'A test fails if our published sub-processor list drifts from the services actually configured',
    ],
    verify: 'pnpm test:integration -- dogfood',
  },
  {
    id: 'O-02', stream: 'O', phase: 6, est: 'M', depends: ['C-04'],
    title: 'Retention and deletion jobs',
    goal: 'Everything the system holds has a declared lifetime and a job that enforces it.',
    acceptance: [
      'Every table declares a retention rule; a table without one fails a CI check',
      'Unclaimed cases and their evidence expire automatically',
      'Deletion is verified by a test that asserts blobs are gone, not only rows',
    ],
    verify: 'pnpm test:integration -- retention',
  },
  {
    id: 'O-03', stream: 'O', phase: 2, est: 'S', depends: ['R-03'],
    title: 'Claim discipline in customer-facing language',
    goal: 'A reviewed vocabulary: never certificate, never approved, never a named vendor called unlawful.',
    acceptance: [
      'A banned-phrase check runs over all customer-facing content in every locale and fails the build',
      'Third-party findings are phrased as observable behaviour plus a cited decision',
      'Disclaimer appears on the case page and every export, not buried in terms',
    ],
    verify: 'pnpm run check:claims',
    notes: 'Cheap to build, expensive to omit. Covers the three legal risks named in §13 of the concept doc.',
  },
  {
    id: 'O-04', stream: 'O', phase: 6, est: 'M', depends: ['F-06'],
    title: 'Observability',
    goal: 'Traces, structured logs and metrics for scans, jobs, model calls and verifier rejections.',
    acceptance: [
      'A scan can be reconstructed end to end from its trace',
      'Model cost and latency tracked per task type',
      'Verifier rejection rate is a first-class dashboard metric — a sudden drop means the gate broke',
      'No personal data in logs, asserted by a test that scans log output',
    ],
    verify: 'pnpm test:integration -- observability',
  },
  {
    id: 'O-05', stream: 'O', phase: 6, est: 'M', depends: ['T-12'],
    title: 'The delivery gate',
    goal: 'One command that decides whether this is fit to hand over.',
    acceptance: [
      'Runs every suite, the canary comparison and the manual smoke script, and prints a single verdict',
      'Any red is a hard stop with a named owner and task id',
      'Produces a signed, dated report stored in artifacts/',
      'Documented in README so it can be run by someone who has not read this plan',
    ],
    verify: 'pnpm run gate',
  },

  {
    id: 'V-01', stream: 'V', phase: 3, est: 'L', depends: ['C-02', 'A-08'],
    title: 'Status report, generated at any moment',
    goal: 'A PDF a person can hand to a colleague, a board or an auditor, produced from the case as it stands right now — not only when finished.',
    acceptance: [
      'Status matrix by area, with an explicit not-determined state that is never dressed up as a pass',
      'Numbered action points carrying owner and effort, ordered the same way the plan is',
      'Every article the report relies on is quoted in full from the corpus, with a resolvable reference',
      'Reproducible: the same case at the same point produces an identical document',
      'Readable printed in greyscale, and carries the case URL so a reader can get to the live version',
      'Regenerating is one click and always available, including mid-progress',
    ],
    verify: 'pnpm test:integration -- report-render',
    notes: 'The report is the artefact that travels. Someone who never ran the scan will read it first.',
  },
  {
    id: 'V-02', stream: 'V', phase: 5, est: 'L', depends: ['A-01', 'A-08', 'A-07'],
    title: 'Case-grounded advisor',
    goal: 'An assistant holding two things at once — the full legal corpus, and the actual case — so it can answer "we have this, do we need that?"',
    acceptance: [
      'Every answer separates three things: the answer, what this case says, and what the law says',
      'Facts about the company come from the graph with a link to the evidence, never from the model',
      'Retrieval is jurisdiction-filtered; a Danish case never gets German law as authority',
      'Refuses to answer where the case has no evidence, and says which question would settle it',
      'Answers can be appended to the report, carrying their citations',
      'Runs on the self-hosted stack — a customer case never leaves the tenant',
    ],
    verify: 'pnpm test:evals -- advisor',
    notes: 'Reuses the corpus and EU inference behind gdprchat.eu. The new part is grounding in the case, which is what makes it worth building rather than pointing people at the existing chat.',
  },
  {
    id: 'V-03', stream: 'V', phase: 5, est: 'M', depends: ['V-02'],
    title: 'Verbatim law, guaranteed',
    goal: 'Show legal text word for word, and make it structurally impossible for a model to be the thing that typed it.',
    acceptance: [
      'Quoted passages are fetched from the corpus by identifier and rendered without passing through a model',
      'A rendered quotation is compared character for character against the corpus entry before it is displayed',
      'Truncation, ellipsis or annotation inside a quotation fails the check rather than degrading quietly',
      'Every quotation carries instrument, article and paragraph, and the corpus version it came from',
      'Consolidated text is dated, so an amended article is never shown as current without its date',
    ],
    verify: 'pnpm test:integration -- verbatim && pnpm run check:citations',
  },
  {
    id: 'V-04', stream: 'V', phase: 5, est: 'M', depends: ['V-02', 'A-10'],
    title: 'Advisor safety and limits',
    goal: 'It is an assistant, not counsel, and the interface has to carry that without becoming a nag.',
    acceptance: [
      'Not-legal-advice notice present on the surface and on every export, never only in terms',
      'Answers rather than deflects: escalation appears only after a genuine attempt, never as a first response to a hard question',
      'Case content is untrusted input: a policy or contract that tries to instruct the advisor is rejected',
      'Conversations are tenant-scoped and deletable with the case',
      'An eval set of 20 questions it should refuse, with the expected refusal shape',
    ],
    verify: 'pnpm test:evals -- advisor-safety && pnpm test:adversarial -- advisor',
  },
  {
    id: 'V-05', stream: 'V', phase: 5, est: 'L', depends: ['V-02'],
    title: 'Dive points on every element',
    goal: 'Any finding, step, quoted article or phrase opens a conversation already scoped to it. Modelled on GDPRchat Zen dive-deeper — see docs/decisions/dive-points.md.',
    acceptance: [
      'A dive from a page seeds turn zero with the fragment, the case as structured fact, and jurisdiction-filtered corpus; after that it is an ordinary conversation and further dives append',
      'Fragment handling matches GDPRchat: markdown stripped, capped at 300 characters, prefixed with the localised Tell me more about this',
      'Gating carried over: nothing to expand, and elements that already offer a specific next action, get no dive point',
      'The fragment is delimited and labelled as quoted data — it often originates from the customer website or a contract',
      'Retrieval re-runs scoped to the fragment rather than to the whole case',
      'Every dive is a timeline event, so the case shows what was asked about',
    ],
    verify: 'pnpm test:evals -- dive-points && pnpm test:adversarial -- dive-injection',
    notes: 'The mechanism in GDPRchat is about fifteen lines because the conversation already holds the context. Ours has to build turn zero, and that is the whole task.',
  },
  // ---------------------------------------------------------------- TESTING
  {
    id: 'T-01', stream: 'T', phase: 2, est: 'L', depends: ['F-07'],
    title: 'The fixture site suite',
    goal: 'Twenty-five deliberately broken websites, each isolating known violations, plus clean controls.',
    acceptance: [
      'Every launch finding type has at least one positive and one negative fixture',
      'At least four fixtures are clean sites that must produce zero findings',
      'Fixtures cover the awkward cases: lazy-loaded trackers, banners in shadow DOM, iframes, single-page apps, consent stored in localStorage rather than cookies',
      'Adding a fixture requires no code change',
    ],
    verify: 'pnpm test:integration -- fixture-suite',
    notes: 'This is the substitute for a human tester. Its coverage is the ceiling on how much anyone can trust the scanner.',
  },
  {
    id: 'T-02', stream: 'T', phase: 2, est: 'M', depends: ['T-01'],
    title: 'Golden expectations and the differ',
    goal: 'Compare produced findings against expected.json with a readable diff, and make updating a golden a deliberate act.',
    acceptance: [
      'Diff output names exactly which finding was missing, extra or changed',
      'Updating goldens requires an explicit flag and shows what changed',
      'A silently changed golden is caught in review because the diff is committed',
    ],
    verify: 'pnpm test:integration -- goldens',
  },
  {
    id: 'T-03', stream: 'T', phase: 2, est: 'M', depends: ['A-08'],
    title: 'Citation resolution suite',
    goal: 'Prove that no citation the system can emit is fabricated.',
    acceptance: [
      'Every citation in every rule, remedy, guide and generated document resolves to a real corpus paragraph',
      'Quoted text is confirmed present at that location by exact match',
      'Runs over the whole content set in CI, not a sample',
    ],
    verify: 'pnpm run check:citations',
  },
  {
    id: 'T-04', stream: 'T', phase: 2, est: 'M', depends: ['F-04'],
    title: 'Schema conformance for every model output',
    goal: 'No model output enters the system unvalidated, and malformed output has a defined behaviour.',
    acceptance: [
      'Every model call site validates against its Zod schema',
      'Fuzzed and truncated responses are handled deterministically — retry once, then fail loudly',
      'A test enumerates model call sites and fails if any lacks validation',
    ],
    verify: 'pnpm test:unit -- schema-conformance',
  },
  {
    id: 'T-05', stream: 'T', phase: 5, est: 'L', depends: ['A-06', 'A-07'],
    title: 'Behavioural eval sets',
    goal: 'Fixed scenario sets with expected judgements for the planner, the verifier, the policy reader and the DPA reader.',
    acceptance: [
      'Each set has at least 20 labelled scenarios with documented reasoning',
      'Pass thresholds are declared per set and enforced in CI',
      'Results are tracked over time so a prompt change that degrades quality is visible',
      'Evals run against the self-hosted model configuration, not only a hosted one',
    ],
    verify: 'pnpm test:evals',
  },
  {
    id: 'T-06', stream: 'T', phase: 2, est: 'L', depends: ['A-10'],
    title: 'Adversarial suite',
    goal: 'Attack the product the way a hostile site would.',
    acceptance: [
      'Prompt injection in page text, comments, alt text, CSS content, JSON-LD, the policy and the processing agreement',
      'Scanner-detection cloaking: a fixture that serves clean content to our user agent and trackers to everyone else, which must be detected and reported',
      'Resource exhaustion: infinite redirects, enormous documents, slow loris, zip bombs in linked files',
      'Attempts to make the scanner act as an open proxy or reach internal addresses — all blocked',
      'Any successful attack fails the build',
    ],
    verify: 'pnpm test:adversarial',
  },
  {
    id: 'T-07', stream: 'T', phase: 1, est: 'M', depends: ['F-05'],
    title: 'Tenancy and access-control suite',
    goal: 'Systematically attempt to read or write across tenant and case boundaries.',
    acceptance: [
      'Covers direct queries, joins, aggregates, job payloads, export endpoints and invitation links',
      'Includes an authenticated user of tenant A attempting every route belonging to tenant B',
      'Runs on every push, not nightly',
    ],
    verify: 'pnpm test:integration -- tenancy-matrix',
  },
  {
    id: 'T-08', stream: 'T', phase: 6, est: 'M', depends: ['I-02'],
    title: 'Jurisdiction matrix suite',
    goal: 'The same fixture scanned as several countries must yield identical finding identities and different bindings.',
    acceptance: [
      'Finding ids identical across jurisdictions; citations, authorities and guide text differ',
      'No cross-jurisdiction leakage — a Danish authority never appears in a German case',
      'Unsupported jurisdiction degrades explicitly and the test asserts the message',
    ],
    verify: 'pnpm test:integration -- jurisdiction-matrix',
  },
  {
    id: 'T-09', stream: 'T', phase: 3, est: 'L', depends: ['U-04', 'C-05'],
    title: 'End-to-end journeys',
    goal: 'The real paths a person takes, driven through the browser.',
    acceptance: [
      'Scan → case opens → read a finding → apply a fix → re-check → watch it close',
      'Invite a colleague → they complete their list → the register fills → progress updates',
      'Deep scan → answer three questions → new findings appear → generate an artefact → sign it off',
      'Export the case, then delete it, and assert it is gone',
      'Each journey runs against the fixture estate, deterministically, in CI',
    ],
    verify: 'pnpm test:e2e',
  },
  {
    id: 'T-10', stream: 'T', phase: 6, est: 'M', depends: ['T-02'],
    title: 'Canary corpus and drift alarm',
    goal: 'Two hundred real, stable public sites scanned nightly, compared day over day, to catch what fixtures never will.',
    acceptance: [
      'Nightly run produces a diff against yesterday, with unexpected changes raised',
      'Distinguishes a site that changed from a scanner that changed — by re-running the previous scanner build on the same snapshot',
      'Sites are public, scanned politely, and the corpus excludes anyone who asks to be excluded',
      'Alarm has a human owner and a documented triage procedure',
    ],
    verify: 'pnpm run canary:check',
    notes: 'Fixtures prove the scanner does what we designed. The canary proves it still works on the actual internet.',
  },
  {
    id: 'T-11', stream: 'T', phase: 6, est: 'S', depends: ['S-05'],
    title: 'Performance budget',
    goal: 'The front door promise is sixty seconds. Hold it.',
    acceptance: [
      'Three-pass scan completes within 60s at the 95th percentile against the fixture estate',
      'Deep scan completes within 10 minutes or streams partial results',
      'Budgets are asserted in CI and a regression fails the build',
    ],
    verify: 'pnpm test:perf',
  },
  {
    id: 'T-12', stream: 'T', phase: 6, est: 'M', depends: ['T-06', 'T-09', 'T-10'],
    title: 'Delivery gate script and manual smoke checklist',
    goal: 'One command, one verdict, plus the short list of things a human should still look at with their own eyes.',
    acceptance: [
      'Aggregates every suite plus canary status into a single pass or fail',
      'Manual checklist is under fifteen items and each is a yes-or-no observation, not a judgement call',
      'Produces the handover report referenced in O-05',
    ],
    verify: 'pnpm run gate -- --dry-run',
    notes: 'The manual list is deliberately tiny. Everything else has to be automated, because the user cannot test this by hand.',
  },
];
